name: audioplayers
description: A flutter plugin to play multiple audio files simultaneously
version: 0.13.6
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^2.0.0
  path_provider: ^1.1.0
  path_provider_macos: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.11.3+17
  test: ^1.3.0

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
